/* ============================================================
   emoji.js — catálogo de emoji del sistema con nombres y
   palabras clave en español para el buscador.
   Formato compacto: [emoji, nombre, categoria, palabrasClave]
   ============================================================ */

const E = [

/* ---------- Fiesta ---------- */
['🎉','Confeti','Fiesta',['confeti','fiesta','celebrar','party','popper']],
['🎊','Bola de confeti','Fiesta',['confeti','fiesta','celebrar','party']],
['🎈','Globo','Fiesta',['globo','balloon','fiesta','cumpleanos']],
['🎁','Regalo','Fiesta',['regalo','gift','presente','cumpleanos','navidad']],
['🎀','Moño','Fiesta',['mono','lazo','regalo','ribbon']],
['🪅','Piñata','Fiesta',['pinata','fiesta','cumpleanos']],
['🎇','Fuegos artificiales','Fiesta',['fuegos','artificiales','fiesta','celebracion']],
['🎆','Fuegos en el cielo','Fiesta',['fuegos','artificiales','noche','ano nuevo']],
['🕯️','Vela','Fiesta',['vela','candle','luz','cumpleanos']],
['🥂','Brindis','Fiesta',['brindis','copa','champan','celebrar','cheers']],
['🍾','Champán','Fiesta',['champan','botella','celebrar','brindis']],
['🎃','Calabaza','Fiesta',['calabaza','halloween','noche de brujas']],
['🎄','Árbol de Navidad','Fiesta',['navidad','arbol','christmas','pino']],
['🎅','Papá Noel','Fiesta',['papa noel','santa','navidad']],
['🧑‍🎄','Duende navideño','Fiesta',['duende','navidad','elfo']],
['👑','Corona','Fiesta',['corona','rey','reina','ganar','premio']],
['🏆','Trofeo','Fiesta',['trofeo','premio','ganar','campeon','meta']],
['🥇','Medalla de oro','Fiesta',['oro','medalla','premio','primero','ganar']],
['🥳','Carita de fiesta','Fiesta',['fiesta','cumpleanos','celebrar','carita']],
['🎤','Micrófono','Fiesta',['microfono','cantar','karaoke','concierto']],
['🎸','Guitarra','Fiesta',['guitarra','musica','concierto','rock']],
['🎵','Nota musical','Fiesta',['musica','nota','cancion','melodia']],
['🎬','Claqueta','Fiesta',['pelicula','cine','movie','video']],
['🎨','Paleta de pintura','Fiesta',['pintura','arte','colores','creatividad']],
['🎯','Diana','Fiesta',['diana','meta','objetivo','tiro','target']],
['🎮','Videojuego','Fiesta',['videojuego','juego','gamer','consola']],
['🪄','Varita mágica','Fiesta',['varita','magia','truco','magico']],
['🎭','Teatro','Fiesta',['teatro','obra','actuar','mascaras']],

/* ---------- Comida ---------- */
['🎂','Torta de cumpleaños','Comida',['torta','pastel','cumpleanos','cake','birthday','vela']],
['🍰','Porción de torta','Comida',['torta','pastel','cake','postre','porcion']],
['🧁','Magdalena','Comida',['magdalena','cupcake','muffin','postre']],
['🍩','Dona','Comida',['dona','donut','rosquilla','postre']],
['🍪','Galleta','Comida',['galleta','cookie','postre','navidad']],
['🍫','Chocolate','Comida',['chocolate','dulce','barra','cacao']],
['🍬','Caramelo','Comida',['caramelo','dulce','candy']],
['🍭','Piruleta','Comida',['piruleta','paleta','dulce','lollipop']],
['🍦','Helado de cono','Comida',['helado','cono','postre','verano']],
['🍧','Raspadito','Comida',['raspado','granizado','helado','verano']],
['🥧','Tarta','Comida',['tarta','pie','pastel','postre','horno']],
['☕','Café','Comida',['cafe','taza','coffee','desayuno','caliente']],
['🍵','Té','Comida',['te','infusion','taza','caliente']],
['🫖','Tetera','Comida',['tetera','te','infusion']],
['🥤','Vaso con pajita','Comida',['refresco','gaseosa','vaso','bebida']],
['🧃','Jugo','Comida',['jugo','zumo','caja','bebida']],
['🥛','Vaso de leche','Comida',['leche','milk','vaso','bebida']],
['🍺','Cerveza','Comida',['cerveza','birra','bar','beer']],
['🍷','Copa de vino','Comida',['vino','copa','tinto','wine']],
['🍕','Pizza','Comida',['pizza','porcion','italiana','cena']],
['🍔','Hamburguesa','Comida',['hamburguesa','burger','comida','almuerzo']],
['🌭','Perro caliente','Comida',['perro caliente','hot dog','salchicha']],
['🌮','Taco','Comida',['taco','mexicana','comida']],
['🌯','Burrito','Comida',['burrito','wrap','mexicana']],
['🥟','Empanada','Comida',['empanada','dumpling','masa']],
['🍟','Papas fritas','Comida',['papas','fritas','french fries','acompanante']],
['🥗','Ensalada','Comida',['ensalada','verduras','saludable','vegetal']],
['🍜','Ramen','Comida',['ramen','sopa','fideos','japonesa']],
['🍣','Sushi','Comida',['sushi','japonesa','arroz','rollo']],
['🍱','Bento','Comida',['bento','japonesa','lonchera','comida']],
['🍚','Arroz','Comida',['arroz','guarnicion','grano']],
['🍛','Curry','Comida',['curry','arroz','india','guiso']],
['🍢','Brocheta','Comida',['brocheta','pincho','parrilla']],
['🍤','Camarón','Comida',['camaron','gamba','shrimp','marisco']],
['🦐','Camarón entero','Comida',['camaron','marisco','gamba']],
['🦀','Cangrejo','Comida',['cangrejo','marisco','crab']],
['🐟','Pescado','Comida',['pescado','pez','fish','marisco']],
['🥩','Corte de carne','Comida',['carne','bife','steak','parrilla']],
['🍗','Pollo','Comida',['pollo','muslo','asado','chicken']],
['🥓','Tocino','Comida',['tocino','beicon','bacon','desayuno']],
['🥚','Huevo','Comida',['huevo','egg','desayuno','proteina']],
['🍳','Huevo frito','Comida',['huevo','frito','sarten','desayuno']],
['🧀','Queso','Comida',['queso','cheese','lacteo']],
['🥞','Panqueques','Comida',['panqueque','hotcake','desayuno']],
['🧇','Waffle','Comida',['waffle','desayuno','dulce']],
['🍞','Pan','Comida',['pan','bread','tostada']],
['🥐','Croissant','Comida',['croissant','medialuna','pan','desayuno']],
['🥖','Baguette','Comida',['baguette','pan','frances']],
['🥨','Pretzel','Comida',['pretzel','pan','salado']],
['🫓','Pan plano','Comida',['pan plano','tortilla','naan','pita']],
['🥯','Rosca de pan','Comida',['bagel','rosca','pan']],
['🍠','Camote','Comida',['camote','boniato','papa dulce']],
['🥔','Papa','Comida',['papa','patata','tuberculo']],
['🥕','Zanahoria','Comida',['zanahoria','verdura','carrot']],
['🥦','Brócoli','Comida',['brocoli','verdura','saludable']],
['🥬','Lechuga','Comida',['lechuga','col','verdura','verde']],
['🍅','Tomate','Comida',['tomate','tomato','verdura','ensalada']],
['🥑','Aguacate','Comida',['aguacate','palta','avocado','verde']],
['🌽','Maíz','Comida',['maiz','choclo','elote','verdura']],
['🧄','Ajo','Comida',['ajo','garlic','condimento']],
['🧅','Cebolla','Comida',['cebolla','onion','condimento']],
['🍄','Champiñón','Comida',['champinon','hongo','seta','mushroom']],
['🍎','Manzana roja','Comida',['manzana','apple','fruta']],
['🍏','Manzana verde','Comida',['manzana','verde','fruta']],
['🍌','Plátano','Comida',['platano','banana','fruta','guineo']],
['🍇','Uvas','Comida',['uvas','fruta','racimo','vino']],
['🍓','Fresa','Comida',['fresa','frutilla','strawberry','fruta']],
['🍊','Mandarina','Comida',['mandarina','naranja','fruta','citrico']],
['🍋','Limón','Comida',['limon','citrico','fruta']],
['🍉','Sandía','Comida',['sandia','melon','fruta','verano']],
['🍍','Piña','Comida',['pina','ananas','fruta','tropical']],
['🥭','Mango','Comida',['mango','fruta','tropical']],
['🥥','Coco','Comida',['coco','fruta','tropical']],
['🍑','Durazno','Comida',['durazno','melocoton','peach','fruta']],
['🍐','Pera','Comida',['pera','pear','fruta']],
['🍒','Cerezas','Comida',['cereza','cherry','fruta']],
['🫐','Arándanos','Comida',['arandano','blueberry','fruta','berry']],
['🥜','Maní','Comida',['mani','cacahuete','fruto seco','peanut']],
['🌰','Castaña','Comida',['castana','nuez','fruto seco']],
['🍯','Miel','Comida',['miel','honey','dulce']],
['🧂','Sal','Comida',['sal','condimento','salt']],
['🥣','Tazón de cereal','Comida',['tazon','cereal','desayuno','bowl']],
['🍽️','Plato con cubiertos','Comida',['plato','cubiertos','cena','comida']],
['🥡','Comida para llevar','Comida',['llevar','takeout','delivery','comida']],
['🍶','Sake','Comida',['sake','botella','japonesa']],

/* ---------- Mascotas y animales ---------- */
['🐶','Perro','Mascotas',['perro','dog','mascota','cachorro','paseo']],
['🐕','Perro sentado','Mascotas',['perro','mascota','can','paseo']],
['🐱','Gato','Mascotas',['gato','cat','mascota','michi','minino']],
['🐈','Gato andando','Mascotas',['gato','mascota','felino']],
['🐭','Ratón','Mascotas',['raton','mouse','roedor']],
['🐹','Hámster','Mascotas',['hamster','roedor','mascota']],
['🐰','Conejo','Mascotas',['conejo','rabbit','liebre','mascota']],
['🦊','Zorro','Mascotas',['zorro','fox','animal']],
['🐻','Oso','Mascotas',['oso','bear','peluche','animal']],
['🐼','Panda','Mascotas',['panda','animal','oso']],
['🐨','Koala','Mascotas',['koala','animal','australia']],
['🐯','Tigre','Mascotas',['tigre','tiger','felino','animal']],
['🦁','León','Mascotas',['leon','lion','animal','salvaje']],
['🐮','Vaca','Mascotas',['vaca','cow','animal','granja']],
['🐷','Cerdo','Mascotas',['cerdo','chancho','pig','granja']],
['🐸','Rana','Mascotas',['rana','frog','sapo','animal']],
['🐵','Mono','Mascotas',['mono','monkey','animal']],
['🐔','Gallina','Mascotas',['gallina','pollo','granja','chicken']],
['🐣','Pollito','Mascotas',['pollito','huevo','granja','pascua']],
['🐧','Pingüino','Mascotas',['pinguino','penguin','animal','frio']],
['🐦','Pájaro','Mascotas',['pajaro','bird','ave','animal']],
['🦜','Loro','Mascotas',['loro','parrot','ave','tropical']],
['🦆','Pato','Mascotas',['pato','duck','ave','agua']],
['🦉','Búho','Mascotas',['buho','lechuza','owl','noche']],
['🦢','Cisne','Mascotas',['cisne','swan','ave']],
['🦩','Flamenco','Mascotas',['flamenco','ave','rosa']],
['🦇','Murciélago','Mascotas',['murcielago','bat','halloween']],
['🐺','Lobo','Mascotas',['lobo','wolf','animal']],
['🐴','Caballo','Mascotas',['caballo','horse','equitacion']],
['🦄','Unicornio','Mascotas',['unicornio','unicorn','magico']],
['🐝','Abeja','Mascotas',['abeja','bee','miel','insecto']],
['🦋','Mariposa','Mascotas',['mariposa','butterfly','insecto']],
['🐌','Caracol','Mascotas',['caracol','snail','lento']],
['🐞','Mariquita','Mascotas',['mariquita','catarina','insecto']],
['🕷️','Araña','Mascotas',['arana','spider','insecto']],
['🐢','Tortuga','Mascotas',['tortuga','turtle','lento']],
['🐍','Serpiente','Mascotas',['serpiente','culebra','snake']],
['🦎','Lagarto','Mascotas',['lagarto','lagartija','reptil']],
['🦖','Dinosaurio','Mascotas',['dinosaurio','dino','trex']],
['🐙','Pulpo','Mascotas',['pulpo','octopus','mar']],
['🐠','Pez tropical','Mascotas',['pez','fish','acuario','tropical']],
['🐬','Delfín','Mascotas',['delfin','dolphin','mar']],
['🐳','Ballena','Mascotas',['ballena','whale','mar']],
['🦈','Tiburón','Mascotas',['tiburon','shark','mar']],
['🦭','Foca','Mascotas',['foca','mar','seal']],
['🦓','Cebra','Mascotas',['cebra','zebra','animal']],
['🦒','Jirafa','Mascotas',['jirafa','giraffe','animal']],
['🐘','Elefante','Mascotas',['elefante','elephant','animal']],
['🦥','Perezoso','Mascotas',['perezoso','sloth','animal']],
['🦔','Erizo','Mascotas',['erizo','hedgehog','animal']],
['🐿️','Ardilla','Mascotas',['ardilla','squirrel','animal']],
['🦴','Hueso','Mascotas',['hueso','bone','perro','premio']],
['🐾','Huellas','Mascotas',['huella','paw','mascota','pisadas']],
['🪺','Nido','Mascotas',['nido','nest','huevos','ave']],

/* ---------- Naturaleza ---------- */
['☀️','Sol','Naturaleza',['sol','sun','dia','clima','verano']],
['🌞','Sol con cara','Naturaleza',['sol','sun','feliz','clima']],
['🌤️','Sol con nubes','Naturaleza',['sol','nubes','clima','parcial']],
['⛅','Parcialmente nublado','Naturaleza',['nublado','clima','sol']],
['☁️','Nube','Naturaleza',['nube','cloud','clima','cielo']],
['🌧️','Lluvia','Naturaleza',['lluvia','rain','clima','paraguas']],
['⛈️','Tormenta','Naturaleza',['tormenta','rayo','clima','storm']],
['🌈','Arcoíris','Naturaleza',['arcoiris','rainbow','color','clima']],
['❄️','Copo de nieve','Naturaleza',['nieve','snow','frio','invierno']],
['⛄','Muñeco de nieve','Naturaleza',['nieve','muneco','invierno','navidad']],
['🌙','Luna','Naturaleza',['luna','moon','noche','dormir']],
['🌝','Luna llena','Naturaleza',['luna','llena','noche','moon']],
['⭐','Estrella','Naturaleza',['estrella','star','noche','favorito']],
['🌟','Estrella brillante','Naturaleza',['estrella','brillo','star','destacar']],
['✨','Destellos','Naturaleza',['brillos','destellos','sparkle','nuevo']],
['🔥','Fuego','Naturaleza',['fuego','fire','racha','caliente','energia']],
['🌊','Ola','Naturaleza',['ola','mar','agua','wave','playa']],
['💧','Gota','Naturaleza',['gota','agua','drop','lluvia']],
['🌱','Brote','Naturaleza',['brote','planta','verde','crecer','semilla']],
['🌿','Rama','Naturaleza',['rama','hoja','verde','planta']],
['🍀','Trébol','Naturaleza',['trebol','suerte','clover','verde']],
['🌳','Árbol','Naturaleza',['arbol','tree','verde','naturaleza']],
['🌲','Pino','Naturaleza',['pino','arbol','navidad','bosque']],
['🌴','Palmera','Naturaleza',['palmera','playa','tropical','vacaciones']],
['🌵','Cactus','Naturaleza',['cactus','desierto','planta']],
['🌻','Girasol','Naturaleza',['girasol','flor','sunflower','amarillo']],
['🌹','Rosa','Naturaleza',['rosa','flor','amor','rose']],
['🌷','Tulipán','Naturaleza',['tulipan','flor','primavera']],
['🌸','Flor de cerezo','Naturaleza',['flor','cerezo','primavera','rosa']],
['🏵️','Flor','Naturaleza',['flor','roseta','planta']],
['💐','Ramo de flores','Naturaleza',['ramo','flores','regalo','bouquet']],
['🍁','Hoja de arce','Naturaleza',['hoja','arce','otono','canada']],
['🍂','Hojas secas','Naturaleza',['hojas','otono','caer']],
['🪴','Planta en maceta','Naturaleza',['planta','maceta','interior','verde']],
['🌾','Espigas','Naturaleza',['espiga','trigo','campo']],
['🪵','Madera','Naturaleza',['madera','lena','tronco','wood']],
['🪨','Piedra','Naturaleza',['piedra','roca','rock']],
['🏔️','Montaña nevada','Naturaleza',['montana','nieve','pico']],
['⛰️','Montaña','Naturaleza',['montana','cerro','mountain']],
['🌋','Volcán','Naturaleza',['volcan','erupcion','lava']],
['🏝️','Isla','Naturaleza',['isla','playa','tropical','vacaciones']],
['🪐','Planeta','Naturaleza',['planeta','espacio','saturno']],
['🌍','Planeta Tierra','Naturaleza',['tierra','mundo','planeta','global']],
['🚀','Cohete','Naturaleza',['cohete','espacio','despegar','lanzar']],

/* ---------- Deporte y salud ---------- */
['⚽','Balón de fútbol','Deporte',['futbol','balon','pelota','soccer','deporte']],
['🏀','Balón de básquet','Deporte',['basquet','baloncesto','balon','basketball']],
['🏈','Balón de fútbol americano','Deporte',['futbol americano','balon','nfl']],
['🎾','Pelota de tenis','Deporte',['tenis','pelota','raqueta','tennis']],
['🏐','Vóley','Deporte',['voley','pelota','volleyball']],
['🏓','Ping pong','Deporte',['ping pong','tenis de mesa','raqueta']],
['🏸','Bádminton','Deporte',['badminton','raqueta','volante']],
['🥊','Guante de boxeo','Deporte',['boxeo','guante','pelea','box']],
['🥋','Artes marciales','Deporte',['karate','judo','artes marciales','taekwondo']],
['🏃','Correr','Deporte',['correr','running','trote','ejercicio','cardio']],
['🚶','Caminar','Deporte',['caminar','andar','paso','walk']],
['🚴','Bicicleta','Deporte',['bici','bicicleta','ciclismo','bike','ejercicio']],
['🏊','Nadar','Deporte',['nadar','natacion','piscina','swim']],
['🧘','Yoga','Deporte',['yoga','meditacion','relax','estiramiento','calma']],
['🏋️','Pesas','Deporte',['pesas','gimnasio','gym','fuerza','entrenar']],
['🤸','Gimnasia','Deporte',['gimnasia','acrobacia','voltereta']],
['⛹️','Baloncesto','Deporte',['baloncesto','basquet','jugador']],
['🏇','Equitación','Deporte',['equitacion','caballo','jinete']],
['⛷️','Esquí','Deporte',['esqui','nieve','invierno']],
['🛹','Skate','Deporte',['skate','patineta','monopatin']],
['🥾','Senderismo','Deporte',['senderismo','bota','caminata','trekking','montana']],
['🩺','Estetoscopio','Deporte',['doctor','medico','salud','consulta','revision']],
['💊','Pastilla','Deporte',['pastilla','medicina','remedio','pildora','salud']],
['💉','Inyección','Deporte',['inyeccion','vacuna','aguja','salud']],
['🩹','Curita','Deporte',['curita','aposito','herida','salud']],
['🦷','Diente','Deporte',['diente','dentista','muela','odontologo']],
['🫀','Corazón anatómico','Deporte',['corazon','salud','organo']],
['❤️','Corazón rojo','Deporte',['corazon','amor','heart','favorito']],
['💚','Corazón verde','Deporte',['corazon','verde','amor']],
['💙','Corazón azul','Deporte',['corazon','azul','amor']],
['💜','Corazón morado','Deporte',['corazon','morado','amor']],
['🧠','Cerebro','Deporte',['cerebro','mente','pensar','idea']],
['👓','Lentes','Deporte',['lentes','gafas','anteojos','optica']],
['💪','Músculo','Deporte',['musculo','fuerza','gimnasio','brazo']],
['😴','Dormir','Deporte',['dormir','sueno','descanso','siesta']],
['🛌','Cama','Deporte',['cama','dormir','descanso','hotel']],
['🚿','Ducha','Deporte',['ducha','banarse','agua','higiene']],
['🧼','Jabón','Deporte',['jabon','lavar','higiene','manos']],
['🪥','Cepillo de dientes','Deporte',['dientes','cepillo','higiene','bano']],

/* ---------- Casa ---------- */
['🏠','Casa','Casa',['casa','hogar','home','familia']],
['🏡','Casa con jardín','Casa',['casa','jardin','hogar','chalet']],
['🏢','Edificio','Casa',['edificio','oficina','departamento','torre']],
['🚪','Puerta','Casa',['puerta','entrada','door','salida']],
['🪟','Ventana','Casa',['ventana','window','luz']],
['🛋️','Sofá','Casa',['sofa','sillon','sala','living']],
['🛏️','Cama','Casa',['cama','dormitorio','bed']],
['🪑','Silla','Casa',['silla','asiento','chair','comedor']],
['🚽','Inodoro','Casa',['inodoro','bano','wc','servicio']],
['🛁','Tina','Casa',['tina','banera','bano','bath']],
['🧹','Escoba','Casa',['escoba','barrer','limpieza','broom']],
['🧺','Canasta de ropa','Casa',['canasta','ropa','lavanderia','colada']],
['🧻','Papel higiénico','Casa',['papel','higienico','bano','rollo']],
['🪣','Balde','Casa',['balde','cubo','limpieza','agua']],
['🧽','Esponja','Casa',['esponja','limpieza','lavar','platos']],
['🔑','Llave','Casa',['llave','key','cerradura','casa','nuevo']],
['🔒','Candado cerrado','Casa',['candado','seguridad','cerrado','privado']],
['🔔','Campana','Casa',['campana','aviso','recordatorio','notificacion']],
['💡','Bombilla','Casa',['idea','bombilla','luz','creatividad','recordar']],
['🔌','Enchufe','Casa',['enchufe','electricidad','cargar','plug']],
['🔋','Batería','Casa',['bateria','carga','energia','battery']],
['📺','Televisor','Casa',['televisor','tele','tv','pelicula']],
['📻','Radio','Casa',['radio','musica','noticias']],
['☎️','Teléfono','Casa',['telefono','llamada','fijo']],
['📱','Celular','Casa',['celular','movil','telefono','smartphone']],
['🖥️','Monitor','Casa',['monitor','computadora','pantalla','escritorio']],
['⌨️','Teclado','Casa',['teclado','escribir','computadora','keyboard']],
['🖱️','Ratón de computadora','Casa',['raton','mouse','computadora','clic']],
['🖨️','Impresora','Casa',['impresora','imprimir','papel','printer']],
['📷','Cámara','Casa',['camara','foto','recuerdo','fotografia']],
['📹','Videocámara','Casa',['video','camara','grabar','vlog']],
['🕰️','Reloj de pared','Casa',['reloj','hora','pared','clock']],
['⏰','Despertador','Casa',['despertador','alarma','hora','levantarse']],
['🧸','Peluche','Casa',['peluche','juguete','oso','nino']],
['🖼️','Cuadro','Casa',['cuadro','marco','foto','decoracion']],
['🪞','Espejo','Casa',['espejo','mirror','bano','reflejo']],
['🗑️','Papelera','Casa',['papelera','basura','tirar','trash']],
['🛍️','Bolsas de compras','Casa',['bolsas','compra','shopping','tienda']],

/* ---------- Estudio y trabajo ---------- */
['📚','Libros','Estudio',['libros','estudiar','leer','biblioteca','read']],
['📖','Libro abierto','Estudio',['libro','leer','estudiar','read','note']],
['📕','Libro rojo','Estudio',['libro','rojo','lectura']],
['📗','Libro verde','Estudio',['libro','verde','lectura']],
['📘','Libro azul','Estudio',['libro','azul','lectura']],
['📓','Cuaderno','Estudio',['cuaderno','notas','apuntes','notebook']],
['📒','Libro de contabilidad','Estudio',['cuaderno','libro','cuentas']],
['📝','Nota','Estudio',['nota','apuntar','escribir','memo']],
['✏️','Lápiz','Estudio',['lapiz','escribir','pencil','dibujar']],
['🖊️','Bolígrafo','Estudio',['boligrafo','lapicero','escribir','pen']],
['🖋️','Pluma','Estudio',['pluma','firma','tinta','caligrafia']],
['🖍️','Crayón','Estudio',['crayon','color','dibujar','nino']],
['🖌️','Pincel','Estudio',['pincel','pintar','arte','brush']],
['📌','Chincheta','Estudio',['chincheta','pin','fijar','recordatorio']],
['📍','Pin de ubicación','Estudio',['pin','ubicacion','lugar','mapa']],
['📎','Clip','Estudio',['clip','sujetar','papel']],
['📏','Regla','Estudio',['regla','medir','ruler','linea']],
['📐','Escuadra','Estudio',['escuadra','triangulo','medir','geometria']],
['🔖','Marcapáginas','Estudio',['marcapaginas','libro','bookmark']],
['🗂️','Fichero','Estudio',['fichero','archivos','organizar','carpetas']],
['📁','Carpeta','Estudio',['carpeta','archivo','folder','documentos']],
['📂','Carpeta abierta','Estudio',['carpeta','abrir','archivo','folder']],
['🗒️','Bloc de notas','Estudio',['bloc','notas','apuntes','notepad']],
['🗓️','Calendario de pared','Estudio',['calendario','mes','fecha','agenda']],
['📅','Calendario','Estudio',['calendario','fecha','mes','plan']],
['⏳','Reloj de arena','Estudio',['reloj','tiempo','espera','timer']],
['⏱️','Cronómetro','Estudio',['cronometro','tiempo','timer','medir']],
['💻','Portátil','Estudio',['portatil','laptop','computadora','teletrabajo']],
['🧮','Ábaco','Estudio',['abaco','calcular','matematicas','contar']],
['🔬','Microscopio','Estudio',['microscopio','ciencia','laboratorio','investigar']],
['🔭','Telescopio','Estudio',['telescopio','astronomia','mirar','ciencia']],
['🎓','Graduación','Estudio',['graduacion','titulo','escuela','curso','estudiar']],
['🎒','Mochila','Estudio',['mochila','escuela','colegio','backpack']],
['🏫','Escuela','Estudio',['escuela','colegio','clases','universidad']],
['💼','Maletín','Estudio',['maletin','trabajo','oficina','reunion']],
['📊','Gráfico de barras','Estudio',['grafico','barras','informe','datos','reunion']],
['📈','Gráfico subiendo','Estudio',['grafico','subir','crecer','ventas','meta']],
['📉','Gráfico bajando','Estudio',['grafico','bajar','perdida','datos']],
['📋','Portapapeles','Estudio',['portapapeles','lista','tareas','checklist']],
['📄','Documento','Estudio',['documento','hoja','papel','archivo']],
['📑','Pestañas de documento','Estudio',['documento','paginas','archivo']],
['✂️','Tijeras','Estudio',['tijeras','cortar','recortar','scissors']],
['📢','Megáfono','Estudio',['megafono','anuncio','aviso','publicidad']],
['🤝','Apretón de manos','Estudio',['acuerdo','trato','reunion','negocio']],
['👔','Corbata','Estudio',['corbata','formal','trabajo','oficina']],
['📞','Llamada','Estudio',['llamada','telefono','contacto','call']],
['✉️','Sobre','Estudio',['sobre','carta','correo','mail']],
['📧','Correo electrónico','Estudio',['correo','email','mail','mensaje']],
['🧾','Recibo','Estudio',['recibo','factura','pago','cuenta','gasto']],
['⚖️','Balanza','Estudio',['balanza','justicia','abogado','legal']],
['🧪','Tubo de ensayo','Estudio',['laboratorio','ciencia','experimento']],
['🏅','Medalla','Estudio',['medalla','premio','logro','reconocimiento']],

/* ---------- Compras ---------- */
['🛒','Carrito de compras','Compras',['carrito','compra','supermercado','groceries']],
['🏷️','Etiqueta','Compras',['etiqueta','precio','oferta','tag','descuento']],
['💰','Bolsa de dinero','Compras',['dinero','plata','presupuesto','ahorro']],
['💵','Billete','Compras',['billete','dinero','pago','efectivo','cash']],
['💳','Tarjeta de crédito','Compras',['tarjeta','credito','pago','banco']],
['🪙','Moneda','Compras',['moneda','dinero','suelto','coin']],
['💎','Diamante','Compras',['diamante','joya','lujo','valor']],
['🏪','Tienda','Compras',['tienda','local','store','compras']],
['🏬','Centro comercial','Compras',['mall','centro comercial','tienda']],
['🏦','Banco','Compras',['banco','dinero','bank','tramite']],
['📦','Caja','Compras',['caja','paquete','envio','pedido','package']],
['🔍','Lupa','Compras',['lupa','buscar','revisar','search']],
['👛','Monedero','Compras',['monedero','cartera','dinero','bolso']],

/* ---------- Viaje ---------- */
['✈️','Avión','Viaje',['avion','vuelo','viaje','plane','vacaciones']],
['🛫','Despegue','Viaje',['despegar','avion','vuelo','salida']],
['🛬','Aterrizaje','Viaje',['aterrizar','avion','llegada','vuelo']],
['🚗','Coche','Viaje',['coche','auto','carro','car','conducir']],
['🚕','Taxi','Viaje',['taxi','transporte','uber']],
['🚌','Autobús','Viaje',['autobus','bus','transporte','micro']],
['🚆','Tren','Viaje',['tren','trenes','estacion','rail']],
['🚇','Metro','Viaje',['metro','subte','subway','transporte']],
['🚲','Bicicleta','Viaje',['bici','bicicleta','paseo','bike']],
['🛵','Scooter','Viaje',['scooter','moto','motito','delivery']],
['🏍️','Moto','Viaje',['moto','motocicleta','motorcycle']],
['⛽','Gasolina','Viaje',['gasolina','combustible','bomba','gas']],
['⛴️','Ferry','Viaje',['ferry','barco','transbordador']],
['⛵','Velero','Viaje',['velero','barco','vela','sailboat']],
['🚢','Barco','Viaje',['barco','crucero','ship','mar']],
['🗺️','Mapa','Viaje',['mapa','map','ruta','ubicacion','viaje']],
['🧳','Maleta','Viaje',['maleta','equipaje','viaje','suitcase','aeropuerto']],
['🛂','Control de pasaportes','Viaje',['pasaporte','migracion','control','viaje']],
['🎫','Ticket','Viaje',['ticket','boleto','entrada','voucher']],
['📸','Cámara de fotos','Viaje',['camara','foto','souvenir','recuerdo']],
['🗼','Torre','Viaje',['torre','paris','monumento','viaje']],
['🗽','Estatua de la libertad','Viaje',['estatua','libertad','nueva york','viaje']],
['🏰','Castillo','Viaje',['castillo','palacio','tour','viaje']],
['🎡','Rueda de la fortuna','Viaje',['rueda','feria','parque','diversion']],
['🎢','Montaña rusa','Viaje',['montana rusa','roller coaster','parque','diversion']],
['🎠','Carrusel','Viaje',['carrusel','tiovivo','feria','ninos']],
['🧭','Brújula','Viaje',['brujula','direccion','norte','orientacion']],
['🏕️','Camping','Viaje',['camping','carpa','acampada','naturaleza']],
['🏖️','Playa','Viaje',['playa','beach','verano','vacaciones','arena']],
['🅿️','Estacionamiento','Viaje',['parking','estacionamiento','aparcar','auto']],

/* ---------- Ánimo y varios ---------- */
['😀','Carita sonriente','Ánimo',['carita','feliz','sonrisa','smile','bien']],
['😄','Carita contenta','Ánimo',['carita','feliz','contento','alegre']],
['😊','Carita tímida','Ánimo',['carita','feliz','timido','gusto']],
['😍','Carita enamorada','Ánimo',['carita','amor','encanto','ojos de corazon']],
['🤩','Carita asombrada','Ánimo',['carita','asombro','estrellas','wow']],
['😎','Carita con lentes','Ánimo',['carita','lentes','cool','verano']],
['🤗','Carita abrazando','Ánimo',['abrazo','carita','cariño','hug']],
['🤔','Carita pensando','Ánimo',['pensar','duda','carita','idea']],
['😅','Carita sudando','Ánimo',['carita','sudor','uf','nervios']],
['😂','Carita riendo','Ánimo',['risa','llorar de risa','lol','gracioso']],
['🤒','Carita enferma','Ánimo',['enfermo','fiebre','mal','termometro']],
['😢','Carita triste','Ánimo',['triste','llorar','pena','sad']],
['😡','Carita enojada','Ánimo',['enojado','molesto','rabia','angry']],
['😱','Carita asustada','Ánimo',['miedo','susto','grito','shock']],
['🙌','Manos arriba','Ánimo',['manos','celebrar','bravo','logro']],
['👏','Aplausos','Ánimo',['aplauso','bravo','felicitar','clap']],
['👍','Pulgar arriba','Ánimo',['pulgar','ok','bien','aprobado','like']],
['👎','Pulgar abajo','Ánimo',['pulgar','mal','no','dislike']],
['🙏','Manos juntas','Ánimo',['gracias','rezar','por favor','thanks']],
['✌️','Victoria','Ánimo',['victoria','paz','dos','ganar']],
['🤞','Dedos cruzados','Ánimo',['suerte','esperanza','ojala','cruzar']],
['✅','Check verde','Ánimo',['check','hecho','listo','completado','ok']],
['❌','Cruz','Ánimo',['equis','no','cancelar','error','cruz']],
['❗','Signo de exclamación','Ánimo',['importante','atencion','exclamacion','urgente']],
['❓','Signo de interrogación','Ánimo',['pregunta','duda','interrogacion']],
['⚠️','Advertencia','Ánimo',['aviso','cuidado','atencion','warn']],
['🔴','Círculo rojo','Ánimo',['rojo','circulo','urgente','color']],
['🟡','Círculo amarillo','Ánimo',['amarillo','circulo','color','pendiente']],
['🟢','Círculo verde','Ánimo',['verde','circulo','color','hecho']],
['🔵','Círculo azul','Ánimo',['azul','circulo','color','info']],
['🟣','Círculo morado','Ánimo',['morado','circulo','color','violeta']],
['⚫','Círculo negro','Ánimo',['negro','circulo','color']],
['⚪','Círculo blanco','Ánimo',['blanco','circulo','color']],
['🟠','Círculo naranja','Ánimo',['naranja','circulo','color']],
['💯','Cien puntos','Ánimo',['cien','perfecto','excelente','nota']],
['🆕','Nuevo','Ánimo',['nuevo','new','estreno']],
['🆗','OK','Ánimo',['ok','vale','de acuerdo','listo']],
['💤','Dormido','Ánimo',['dormir','sueno','zzz','descanso']],
['💭','Pensamiento','Ánimo',['pensar','idea','nube','reflexion']],
['💬','Globo de diálogo','Ánimo',['hablar','mensaje','chat','comentario']],
['💖','Corazón brillante','Ánimo',['corazon','brillo','amor','bonito']],
['💝','Corazón con lazo','Ánimo',['corazon','regalo','lazo','amor']],
['♻️','Reciclar','Ánimo',['reciclar','reutilizar','eco','medio ambiente']],
['🚫','Prohibido','Ánimo',['prohibido','no','evitar','bloqueado']],
['🔝','Arriba del todo','Ánimo',['arriba','prioridad','top','importante']],
['🎖️','Condecoración','Ánimo',['condecoracion','premio','honor','militar']],
['📌','Alfiler','Ánimo',['alfiler','fijar','importante','pin']],

];

/* ---------- conversión a objetos + índice ---------- */

const norm = (s) => String(s || '')
  .toLowerCase()
  .normalize('NFD')
  .replace(/[\u0300-\u036f]/g, '')
  .replace(/[^a-z0-9\s]/g, ' ')
  .replace(/\s+/g, ' ')
  .trim();

const seen = new Set();

export const EMOJI = E.filter((row) => {
  if (seen.has(row[0])) return false;
  seen.add(row[0]);
  return true;
}).map(([ch, name, cat, keys]) => ({
  kind: 'emo',
  id: ch,
  key: 'emo:' + ch,
  ch,
  name,
  cat,
  keys,
  hay: norm([name, cat].concat(keys).join(' ')),
}));

export const EMOJI_CATS = EMOJI.reduce((acc, s) => {
  if (!acc.includes(s.cat)) acc.push(s.cat);
  return acc;
}, []);
